package:
  name: atuin
  version: 18.2.0
  epoch: 0
  description: Magical shell history
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/atuinsh/atuin
      tag: v${{package.version}}
      expected-commit: a0231a70950fbec9dcc3403e37066d891d1fc833

  - runs: |
      cargo build --locked --release
      cd target/release
      mkdir -p completions
      for sh in 'bash' 'fish' 'zsh'; do
        "./atuin" gen-completions -s "$sh" -o completions/
      done

      install -Dm755 atuin "${{targets.destdir}}"/usr/bin/atuin

      install -Dm 644 "completions/${{package.name}}.bash" "${{targets.destdir}}/usr/share/bash-completion/completions/atuin"
      install -Dm 644 "completions/${{package.name}}.fish" -t "${{targets.destdir}}/usr/share/fish/vendor_completions.d"
      install -Dm 644 "completions/_${{package.name}}" -t "${{targets.destdir}}/usr/share/zsh/site-functions"

  - uses: strip

update:
  enabled: true
  github:
    identifier: atuinsh/atuin
    strip-prefix: v

test:
  pipeline:
    - runs: |
        atuin -V
