package:
  name: bincapz
  version: 0.9.0
  epoch: 0
  description: enumerate binary capabilities, including malicious behaviors
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - yara

environment:
  contents:
    packages:
      - openssl-dev
      - yara-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/chainguard-dev/bincapz/archive/v${{package.version}}/v${{package.version}}.tar.gz
      expected-sha256: 7e2c9de6d8f63d4ead6ff70f2f37b360e06e70307af937c0f519da7c2676ccda

  - uses: go/build
    with:
      packages: .
      ldflags: -s -w
      output: bincapz

  - uses: strip

test:
  environment:
    contents:
      packages:
        - openssl
        - crane
  pipeline:
    - name: Verify bincapz on itself
      runs: |
        set -o pipefail
        bincapz /usr/bin/bincapz | grep Risk: | grep CRITICAL
    - name: Verify bincapz on yara
      runs: |
        set -o pipefail
        bincapz /usr/bin/yara | grep Risk: | grep LOW
    - name: Verify bincapz on openssl
      runs: |
        set -o pipefail
        bincapz /usr/bin/openssl | grep Risk: | grep MEDIUM
    - name: Verify bincapz on crane
      runs: |
        set -o pipefail
        bincapz /usr/bin/crane | grep Risk: | grep MEDIUM
    - name: Verify bincapz diff
      runs: |
        set -o pipefail
        bincapz -diff /usr/bin/openssl /usr/bin/crane | grep "[+]2/MED.*archives/zip"

update:
  enabled: true
  github:
    identifier: chainguard-dev/bincapz
    strip-prefix: v
