package:
  name: erlang-26
  version: 26.2.4
  epoch: 0
  description: General-purpose programming language and runtime environment
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      # mnesia depends on the ca-certificates bundle
      - ca-certificates-bundle
    provides:
      - erlang=26.999.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - ncurses-dev
      - openssl-dev
      - perl-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: b51ad69f57e2956dff4c893bcb09ad68fee23a7f8f6bba7d58449516b696de95
      uri: https://github.com/erlang/otp/releases/download/OTP-${{package.version}}/otp_src_${{package.version}}.tar.gz

  - runs: |
      export CPPFLAGS="-D_BSD_SOURCE $CPPFLAGS"

      ./otp_build autoconf
      ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --host="$CHOST" \
        --build="$CBUILD" \
        --enable-threads \
        --enable-shared-zlib \
        --enable-ssl=dynamic-ssl-lib \
        --enable-jit

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "erlang-26-dev"
    description: "headers for erlang"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - erlang
      provides:
        - erlang-dev=26.999.0

update:
  enabled: true
  github:
    identifier: erlang/otp
    strip-prefix: OTP-
    use-tag: true
    tag-filter: OTP-

test:
  pipeline:
    - runs: |
        erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell
    - runs: |
        cat <<EOF > "hello.erl"
        -module(hello).
        -export([hello_wolfi/0]).

        hello_wolfi() -> io:fwrite("hello, wolfi\n").
        EOF

        erlc hello.erl

        erl -noshell -pa . -eval "hello:hello_wolfi()." -s init stop
