package:
  name: extism
  version: 1.2.0
  epoch: 0
  description: The extism CLI is used to manage Extism installations
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/extism/cli
      tag: v${{package.version}}
      expected-commit: 017d17176d6c3303292dfae2a03ab44fba05cd60

  - uses: go/build
    with:
      modroot: extism
      packages: .
      output: extism

  - uses: strip

update:
  enabled: true
  github:
    identifier: extism/cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        extism -v
        extism lib install
        extism lib versions
