package:
  name: libeconf
  version: 0.6.3
  epoch: 0
  description: Enhanced Config File Parser
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - meson

pipeline:
  - uses: fetch
    with:
      expected-sha256: 98200166785a4d178d30e8b70cfc6296150a6afc900523d6faa242c16039bcd4
      uri: https://github.com/openSUSE/libeconf/archive/refs/tags/v${{package.version}}.tar.gz

  - runs: meson build

  - runs: ninja -C build

  - runs: DESTDIR="${{targets.destdir}}" ninja -C build install

subpackages:
  - range: ""
    name: libeconf-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libeconf
    description: libeconf dev

update:
  enabled: true
  github:
    identifier: openSUSE/libeconf
    strip-prefix: v
