package:
  name: libtbb
  version: 2021.12.0
  epoch: 0
  description: "oneAPI Threading Building Blocks"
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - samurai
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/oneapi-src/oneTBB/archive/v${{package.version}}.tar.gz
      expected-sha256: c7bb7aa69c254d91b8f0041a71c5bcc3936acb64408a1719aec0b2b7639dd84f

  - name: 'Set version and types'
    runs: |
      sed -e "s@#define MALLOC_UNIXLIKE_OVERLOAD_ENABLED __linux__@@"  -i src/tbbmalloc_proxy/proxy.h

  - name: 'Configure libtbb'
    runs: |
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
       -DCMAKE_C_COMPILER=gcc \
       -DCMAKE_CXX_COMPILER=g++ \
       -DCMAKE_BUILD_TYPE=MinSizeRel \
       -DCMAKE_INSTALL_PREFIX=/usr \
       -DCMAKE_INSTALL_LIBDIR=lib \
       -DTBB4PY_BUILD=OFF \
       -DTBB_STRICT=OFF \
       -DTBB_TEST=OFF

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

subpackages:
  - name: "libtbb-dev"
    description: "headers for libtbb"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libtbb

update:
  enabled: true
  github:
    identifier: oneapi-src/oneTBB
    strip-prefix: v
