package:
  name: php-8.2-xdebug
  version: 3.3.2
  epoch: 0
  description: "Step Debugger for PHP"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.2

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-8.2
      - php-8.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/xdebug/xdebug
      tag: "${{package.version}}"
      expected-commit: e978d755861a3a8d9dcef615bb6649b85f266658

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: ./configure

  - uses: autoconf/make

  - name: Make install
    runs: INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "zend_extension=xdebug.so" > "${{targets.subpkgdir}}/etc/php/conf.d/xdebug.ini"

update:
  enabled: true
  github:
    identifier: xdebug/xdebug
    use-tag: true
