package:
  name: py3-argcomplete
  version: 3.3.0
  epoch: 0
  description: Bash/zsh tab completion for argparse
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c7cc834df1fddcf94bd35b740fef7c7ab8e9c350
      repository: https://github.com/kislyuk/argcomplete
      tag: v${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: kislyuk/argcomplete
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - uses: python/import
      with:
        import: argcomplete
