package:
  name: py3-docutils
  version: 0.21.1
  epoch: 0
  description: Documentation Utilities for Python3
  copyright:
    - license: BSD-2-Clause AND GPL-3.0-or-later AND Python-2.0
  dependencies:
    runtime:
      - py3-pip
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/d/docutils/docutils-${{package.version}}.tar.gz
      expected-sha256: 65249d8a5345bc95e0f40f280ba63c98eb24de35c6c8f5b662e3e8948adea83f

  - name: Python Build
    runs: |
      python3 -m pip install flit
      flit build
      FLIT_ROOT_INSTALL=1 flit install

  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}/lib"
      cp -r docutils "${{targets.destdir}}/lib"

  - name: Post Install
    runs: |
      python_version=$(python3 --version | awk '{print $2}' | cut -d'.' -f1,2)
      PYTHON_VERSION="python$python_version"

      mkdir -p "${{targets.destdir}}/usr/lib/${PYTHON_VERSION}/site-packages/"
      cp -r "${{targets.destdir}}/lib/docutils" "${{targets.destdir}}/usr/lib/${PYTHON_VERSION}/site-packages/"

      ln -s "/usr/lib/${PYTHON_VERSION}/site-packages/docutils" "/usr/lib/${PYTHON_VERSION}/site-packages/docutils-${{package.version}}-py3.X.egg-info"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 3849

test:
  pipeline:
    - runs: |
        LIBRARY="docutils"
        IMPORT_STATEMENT="from docutils import nodes"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
