package:
  name: terraform-provider-aws
  version: 5.45.0
  epoch: 0
  description: Terraform AWS provider
  copyright:
    - license: MPL-2.0
  dependencies:
    runtime:
      - terraform
      - terraform-compat
      - terraform-local-provider-config

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/terraform-provider-aws
      tag: v${{package.version}}
      expected-commit: 7769ba5ef892ca70f95d20b82f28b92c6645d35d

  - uses: go/build
    with:
      packages: .
      output: terraform-provider-aws
      ldflags: -s -w

  - runs: |
      GOARCH=$(go env GOARCH)
      mkdir -p "${{targets.destdir}}"/terraform/provider-mirror/registry.terraform.io/hashicorp/aws/${{package.version}}/linux_${GOARCH}/
      ln -s "${{targets.destdir}}"/usr/bin/terraform-provider-aws \
          "${{targets.destdir}}"/terraform/provider-mirror/registry.terraform.io/hashicorp/aws/${{package.version}}/linux_${GOARCH}/terraform-provider-aws_v${{package.version}}_x5

update:
  enabled: true
  github:
    identifier: hashicorp/terraform-provider-aws
    strip-prefix: v
