issuer: https://accounts.google.com

# staging-images: not in use
# prod-images: lifecycle-vs-creator@prod-images-c6e5.iam.gserviceaccount.com
subject: "115891404086175406658"

permissions:
  contents: write
  pull_requests: write
