issuer: https://accounts.google.com

# staging-images: not in use
# prod-images: lifecycle-version-bot@prod-images-c6e5.iam.gserviceaccount.com
subject: "107394578545378987534"

permissions:
  contents: read
